import React from "react"
import { Button } from "../Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/file/O6T7q9Izk6BQ8V2OaKOUlS/Material-3-Design-Kit-(Community)?type=design&node-id=53923-27460&mode=dev",
  {
    props: {
      labeltext: figma.string("Label text"),
      icon: figma.instance("Icon"),
      style: figma.enum("Style", {
        Filled: "filled",
        Outlined: "outlined",
        Text: "text",
        Elevated: "elevated",
        Tonal: "tonal",
      }),
      state: figma.enum("State", {
        enabled: "enabled",
        hovered: "hovered",
        focused: "focused",
        pressed: "pressed",
        disabled: "disabled",
      }),
      showIcon: figma.boolean("Show Icon"),
    },
    example: (props) => <Button
      {...props}
     >Button</Button>,
  },
)
